const tintColorLight = '#f5b74e';
const tintColorDark = '#ffffff';

export const Colors = {
  primary: '#f5b74e',
  blue: '#3f91e4',
  lightblue: '#4b9def',
  red: '#f44336',
  white: '#ffffff',
  black: '#000000',
  grey: '#403f3f',
  lightgrey: '#777676',
  hash: '#e5e5e5',
  darkhash: '#9e9e9e',
  danger: '#ff6054',
  dangerlight: '#ff60547a',
  success: '#4caf50',
  successlight: '#4caf5063',
  info: '#03a9f4',
  infolight: '#22b7fb',
  warning: '#FF9800',
  warninglight: '#ffa622',
  light: {
    text: '#313435',
    background: '#ffffff',
    tint: tintColorLight,
    backgroundTint: '#ffffff',
    tabIconDefault: '#cccccc',
    tabIconSelected: tintColorLight,
    inputBackground: '#f3f3f3d1',
    inputPlaceholder: '#9e9e9e',
    subHeaderTintColor: '#313435',
  },
  dark: {
    text: '#ffffff',
    background: '#2b313a',
    tint: tintColorDark,
    backgroundTint: '#2b313a',
    tabIconDefault: '#cccccc',
    tabIconSelected: tintColorDark,
    inputBackground: '#1d242d',
    inputPlaceholder: '#9e9e9e',
    subHeaderTintColor: '#eeeeee',
  },
};
